### ISSUE TITLE
[feature request] Need to have a flag value of Listview as reversed or not

### ISSUE THREAD

**Issue by rrsaikat** [SebastienBtr/Dash-Chat-2#68]
@LegendAF  @fufesou  @chuusungmin  @SebastienBtr  @kaedeee 
I don't want to reverse my listview by default, so i need a flag into "DashChat" class like this:

         `DashChat(
              isReversed: false,  ///my requested flag 
              currentUser: loggedUser,
              onSend: (ChatMessage m) {
                setState(() {
                  _messages.insert(0, m);
                });
              }`

![image](https://github.com/SebastienBtr/Dash-Chat-2/assets/16695459/0c02f3fd-555e-448e-be43-4e367b291ec4)

**Comment by LegendAF** [comment]
There was some discussion had about this in https://github.com/SebastienBtr/Dash-Chat-2/issues/51

Do you have more context as to what you are trying to accomplish?

**Comment by SebastienBtr** [comment]
Hey, this feature won't be implemented and let me explain a bit why:

- First, it would add a lot of complexity to the package, talking from experience because that was the case on the original Dash Chat package. Because it's not just changing the reverse value, it's also having to change a lot of logic according to it.
- There is no need for this parameter because you can pass your data in the other order
- Fetching your messages by doing a descending order by on the creation date is the expected way, having it in this order forces developers to implement their chat in a more scalable way to enable pagination. You don't do a chat pagination by fetching the oldest message first. You do it like that:

page1: [message30, ..., message20] Where message30 is the last message sent in the chat (the newest message)

Then, if the user scrolls up, you load previous messages and append them to the original list:

page2: [message19, ..., message0]

messages list is now: [message30, ..., message0]

I hope that makes sense and you understand the design choice

**Comment by rrsaikat** [comment]
@SebastienBtr I'm aware of the design pattern of this library and i'm also well known about the points you've mentioned. Nice explanations though. 
@LegendAF At some case i need this, actually i'm running out of time to make fully functional chat UI. Okay no problem, thank you guys.

**Comment by SebastienBtr** [comment]
If you are running out of time and therefore won't change your way of fetching your messages for now, you can do a dirty `.reverse()` on your list of messages until you implement it in a proper way

happy coding!
