### ISSUE TITLE
Did dash_chat_2 0.0.20 supports sendbird_chat_sdk v4 ?

### ISSUE THREAD

**Issue by pshanmukha** [SebastienBtr/Dash-Chat-2#83]
I wanted to use dash chat for UI with sendbird chat sdk, wherever i see tutorial everyone using dash chat ui for sendbird v3 but not v4, So my question is will dash chat supports sendbird chat sdk v4 or not?

**Comment by LegendAF** [comment]
Dash Chat 2 is simply a UI to handle chat data. There should be nothing inherently preventing you from using something like Sendbird. That being said it's not a UI to directly support Sendbird. You may have to create some widgets that otherwise do not exist in Dash Chat 2.

Dash Chat 2 has plenty of "builders" that allow for this and is very flexible.

I don't personally use Sendbird and I am not the maintainer of this plugin. These are just my opinions as someone who uses Dash Chat 2.
